---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-simulator
  labels:
    app: prometheus-simulator
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: prometheus-simulator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-simulator
  labels:
    app: prometheus-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-simulator
  template:
    metadata:
      labels:
        app: prometheus-simulator
    spec:
      containers:
      - name: prometheus-simulator
        image: hermedia/prometheus-simulator:1.0
#        imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        env:
          - name: LISTENING_PORT
            value: "8080"