---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-app-example
  labels:
    app: prometheus-app-example
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: prometheus-app-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-app-example
  labels:
    app: prometheus-app-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-app-example
  template:
    metadata:
      labels:
        app: prometheus-app-example
    spec:
      containers:
      - name: prometheus-app-example
        image: hermedia/prometheus-app-example:1.0
        imagePullPolicy: IfNotPresent
