apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: pv-prometheus
  labels:   
    volume: prometheus
spec:  
  capacity:  
    storage: 20Gi  
  accessModes:  
    -  ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  nfs:  
    path: /opt/nfs/prometheus
    server: 10.10.90.103  
    readOnly: false
---
apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: pv-grafana
  labels: 
    volume: grafana    
spec:  
  capacity:  
    storage: 20Gi  
  accessModes:  
    -  ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  nfs:  
    path: /opt/nfs/grafana
    server: 10.10.90.103  
    readOnly: false
---