apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    k8s-app: grafana
  name: grafana
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    k8s-app: grafana